Feat/pagina erro
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #119
Opened 2024-05-28 11:45 UTC by Joao-Pedro-P-Holanda

# Feature 

## Resolve

#109 

## Descrição

Alterando router da aplicação para definir uma página de erro comum a todas as rotas, e verificar estado de login do usuário sem precisar carregar toda a página. Substituindo Router declarado em App por um dataRouter,em _router/router.tsx_. 

## Adições

- adicionando página de erro que recebe um erro via prop ou pelo hook useRouteError, mostrando ícones e mensagens personalizadas para erros 403 e 404.

- Adicionando componente `Root` com o mesmo conteúdo de App.tsx, mas renderizando uma children passada ou o conteúdo da rota atual dentro da seção main
- Adicionando dataRouter em _router/router.tsx_ com Root como elemento raiz e Erro como errorElement
- Definindo "home" e "acervo/criar-item" como filhas da rota "/" e definindo "home" como a rota index
- Adicionando promise `currentUserPromise`  em  _router/router.tsx_ que retorna o usuário atual ou lança uma Response do react-router caso não exista um usuário logado
- Adicionando componente wrapper  `ProtectedRoutes` que espera pela promise currentUserPromise e retorna o conteúdo na rota protegida requisitada

## Alterações

- Substituindo conteúdo em App por RouteProvider utilizando o router criado

## Remoções

- Removendo estado `logged` e retorno alternativo em _CriarItemAcervo.tsx_ 

## Verificando

### Desenvolvedor

- [ ] Teste de componente/e2e implementados

### Revisor

- [ ] Acessar página não existente direciona para erro 404
- [ ] Acessar página acervo/criar-item sem estar logado redireciona para erro 403
- [ ] Realizar logout enquanto na página acervo/criar-item redireciona para login (erro 404 pois a funcionalidade ainda não foi implementada)
- [ ] Novos testes passam localmente e nos workflows

2024-05-28 12:53 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-05-28 12:53 UTC, Francisco-Paulino-Arruda-Filho commented on src/pages/CriarItemAcervo.tsx
> +import { useNavigate } from "react-router-dom";
Teste executando corretamente nos workflows e localmente

2024-05-28 13:10 UTC, Joao-Pedro-P-Holanda commented on src/pages/CriarItemAcervo.tsx
> +import { useNavigate } from "react-router-dom";
signOut foi realizado pela funcionalidade do Header? 
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/110267046/61bcceb1-b8eb-436c-98f5-07c301848fc7)

Adicionar o código de signOut diretamente força uma nova renderização, então a página seria recarregada, em vez de apenas observar atualizações do usuário

2024-05-29 12:08 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-05-29 12:09 UTC, merged