Feat/item acervo
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #124
Opened 2024-05-29 16:34 UTC by Francisco-Paulino-Arruda-Filho

# Feature Feat/item acervo

## Resolve

#38 parcialmente

## Descrição

Criação da tela de item-acervo

## Adições

itemAcervo.tsx
Criação dos métodos de get, delete e update do item acervo, 
ItemAcervo.test.ts

## Alterações
Rota para a página no App.tsx
useItemAcervoForm.ts
itemAcervoFirebase.ts

## Verificando

### Desenvolvedor

- [x] Teste de componente/e2e implementados
- [x] Criação da tela de ItemAcervo
- [x] Métodos de get, delete e update

### Revisor

- [ ] Verificar se os testes passam localmente e nos workflows
- [ ] Esperar integração do #5 (Sliding-Banner)

2024-05-30 16:36 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +  const itemAcervoStatus = ItemAcervo.status;
Não é necessário atribuir variáveis para cada atributo, em vez disso basta desconstruir os objetos do hook e utilizá-los no resto da página:
```typescript
const {itemAcervo, status, /*outros retornos do hook*/} = useItemAcervo(id)
```
Caso o id seja undefined então deve haver redirecionamento para a página 404.

Exemplo na linha 204: 
```typescript
itemAcervoDataDoacao.format('DD/MM/YYYY')
//equivale a 
itemAcervo?.dataDoacao.format('DD/MM/YYYY')
```

2024-05-30 16:39 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +}))
Botões com a mesma estilização podem usar o mesmo styled

2024-05-30 16:41 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +}))
Não é necessário, material ui já possui o componente Divider
[Documentação do componente](https://mui.com/material-ui/react-divider/)

2024-05-30 16:49 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
Estilizações que são utilizadas apenas uma vez podem ser incluídas no prop sx (para componentes material ui), ou style (componentes react), por exemplo: 
```typescript
const TextoTitulo = styled(Typography)(({ theme }: { theme: Theme }) => ({
  color: theme.palette.tertiary.main,
  // material-theme/display/large
  fontFamily: theme.typography.displayLarge.fontFamily,
  fontSize: '48px',
  fontStyle: 'normal',
  fontWeight: 400,
  lineHeight: '56px', //116.667%
}))
```
Todos os atributos relativos a fonte já estão definidos no tema padrão, então basta utilizar `<Typography variant='displayLarge' color=theme.palette.corUtilizada>Texto</Typography>`

2024-05-30 16:51 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +}))
Pode ser substituído pelo componente Chip, por que um label deve estar vinculado a algum elemento que precise de identificação, e nesse caso é apenas um elemento informativo.
[Documentação do componente](https://mui.com/material-ui/react-chip/)

2024-05-30 16:52 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +  };
não é necessário fazer essa ramificação, basta fazer uma renderização condicional do botão de edição

2024-05-30 16:58 UTC, Joao-Pedro-P-Holanda commented
Adendo: em vez de declarar o divider em cada local utilizado, o componente Stack aceita um prop Divider, [Link da documentação](https://mui.com/material-ui/react-stack/#dividers)

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda requested changes
Dialogs não precisam de atualização na cor de fundo

Cor do texto do título é _onBackground_.

Para capitalizar o texto em um botão existe o prop `textTransform: 'initial'`.

Buscar item com imagens retorna falha por que ao adicionar imagens na página criar-item-acervo, a pasta no storage já está definida
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/110267046/7a750dd4-7168-4058-9d7d-9c824d3005f2)
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/110267046/ddc3382f-433c-429e-ba13-65125dd26774)

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +                        </CheckPrivacidade>
Remover cor utilizada

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +                        </IconButton> : <div></div>
Botão para editar o texto alternativo deve renderizar apenas quando o componente estiver em edição

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +                    </TextoColecao>
Utilizar Typography no lugar

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +                      : <div></div>
Em vez de retornar uma div vazia, é possível retornar o botão apenas com o estado logged=true usando o operador &&

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +          console.log(documentoExiste)
Remover console.log

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda commented on cypress/e2e/ItemAcervo.test.ts
Realizar cy.logout em um bloco `after` em cada cenário de testes

2024-06-04 17:39 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +                    </LabelColecao>
Remover label e diminuir padding do Chip

2024-08-12 18:30 UTC, Joao-Pedro-P-Holanda requested changes
- Não é necessário alterar nenhum método do firebase para lidar com valores dayjs ou timestamp. Basta assegurar que o valor da data enviado ao submeter o formulário é do tipo Date, objetos dayjs possuem o método toDate. DatePickers do formulários continuam utilizando dayjs normalmente, apenas o submit que deve realizar essa conversão
- Texto das seções de texto pode sair do container respectivo na visualização mobile
![image](https://github.com/user-attachments/assets/98cdb61f-56ab-4e6c-bff1-362c816344cc)

2024-08-12 18:30 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +    }));
map não é necessário, basta usar o spread operator [...imagens]

2024-08-12 18:30 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +                          }
Adicionar required aos datepickers

2024-08-12 18:30 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +            return null
Manter erro ao buscar imagem inexistente

2024-08-12 18:30 UTC, Joao-Pedro-P-Holanda commented on src/pages/ItemAcervo.tsx
> +  };
Imagens duplicadas podem ser adicionadas ao sliding banner
![image](https://github.com/user-attachments/assets/ebab0281-cd98-45f1-a1a3-58a04eb56571)
![image](https://github.com/user-attachments/assets/e111ce40-2d73-4676-8d1e-e06848409261)

2024-08-12 18:30 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
>      }
Método adicionarImagens já realiza essa ação e é chamado com as imagens novas nesse método

2024-08-12 18:43 UTC, Francisco-Paulino-Arruda-Filho commented on src/Utils/itemAcervoFirebase.ts
>      }
Não estava sendo editado.

2024-08-12 18:46 UTC, Francisco-Paulino-Arruda-Filho commented on src/pages/ItemAcervo.tsx
> +                              data-cy="controller-checkbox-privado" />} label={undefined}
E o que deveria ser esse label?

2024-08-12 18:46 UTC, Francisco-Paulino-Arruda-Filho commented on src/pages/ItemAcervo.tsx
> +                        </CheckPrivacidade>
E o que eu devaria botar ?

2024-08-13 18:57 UTC, Joao-Pedro-P-Holanda approved these changes

2024-08-13 18:57 UTC, merged