Feat/item acervo firebase
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #145
Opened 2024-07-19 01:45 UTC by Francisco-Paulino-Arruda-Filho

# Feature feat/item-acervo-firebas

## Resolve
#136

## Descrição

Muda o comportamento dos métodos de CRUD

## Adições

Método de mover item de coleção

## Alterações

Refências usadas nos métodos de CRUD

## Verificando

### Desenvolvedor

- Funcionamento dos métodos de CRUD

### Revisor

- [ ] Funcionalidade verificada localmente

2024-07-19 13:27 UTC, Joao-Pedro-P-Holanda requested changes
## **Revisão Parcial**

Revisando inicialmente apenas a lógica do código não relacionada com o caminho onde as informações dos documentos são armazenadas e recuperadas.

### Lançando erros

O primeiro parâmetro de `FirebaseError` é o código do erro, depois a mensagem descrevendo o erro, os parâmetros estão invertidos nas linhas: 99, 102, 109, 222, 274, 282 (mensagem em inglês) e 286.

2024-07-19 13:27 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +      };
Não é necessário criar uma cópia de formData, firebase também já salva tipos Date como Timestamp

2024-07-19 13:27 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +    updateDoc(itemRef, { itemImages: [] }).catch(() => {
updateDoc é chamado para cada imagem removida, e sempre definindo as imagens como um vetor vazio.

Em vez disso o vetor com os caminhos das imagens deve ser igual ao vetor do item antes da remoção sem os elementos passados no parâmetro imagens

2024-07-19 13:27 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +      }
Método remover imagens pode ser utilizado no lugar passando como parâmetro as imagens em `data.imagens`

2024-07-19 13:27 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +      };
Não é necessário copiar formData

2024-07-19 13:27 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +    if (fullPath && typeof fullPath === 'string') {
typeof não é necessário

2024-07-20 12:29 UTC, Joao-Pedro-P-Holanda reviewed
## Caminho dos itens

### Guardando o full path

Não é necessário concatenar "colecoes" antes do fullpath recebido como parâmetro nos métodos `get`, `update` e `delete`, o atributo _ref_ (que vai ser utilizado para armazenar itens de uma exposição) de um documento inclui o caminho completo
Complementando com informações sobre o caminho para armazenar e obter os itens.
- Caminho base é a coleção do firestore "colecoes", que possui dois documentos "publico" e "privado"
- Coleções públicas são armazenadas na subcoleção "lista" do documento "publico" e coleções privadas na subcoleção "lista" do documento "privado"
- Coleções públicas possuem itens públicos e privados, armazenados em subcoleções diferentes "publico" e "privado"
- Coleções privadas possuem uma única subcoleção "itens"

O seguinte formato atende aos requisitos detalhados no esquema do banco:

![image](https://github.com/user-attachments/assets/aecf6727-8f52-4131-9f52-669d0668c907)

2024-07-21 14:38 UTC, Joao-Pedro-P-Holanda reviewed
- Por causa da mudança de caminho o método getNomesColecoes não encontra resultados, queries são realizadas em colecoes/publico/itens. Erro não previsto, além disso, para que o método de adicionar funcione é preciso que o nome da coleção seja passado como parâmetro, em vez de um atributo
![image](https://github.com/user-attachments/assets/5dff6732-e2de-47bb-8b27-aa8e0f881bb9)
- Método remover imagens continua definindo o vetor para vazio em vez de remover apenas as imagens passadas como parâmetro
- Collectionref não precisa ser utilizada com fullpath

2024-07-21 14:38 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
Método de adicionar ainda utiliza o caminho antigo, e apenas o nome da coleção não é suficiente para saber o local a ser adicionado

2024-07-25 11:21 UTC, Joao-Pedro-P-Holanda requested changes

2024-07-25 11:21 UTC, Joao-Pedro-P-Holanda commented on firestore.rules
> +      allow write: if request.auth != null;
Leitura de itens privados em coleções públicas só deve ser permitida para usuários autenticados

2024-07-25 11:21 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +}
Método update não remove imagens que estejam no `itemSelecionado`, mas não em `formData`

2024-07-25 11:21 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +export { methodsItemAcervo, adicionarImagens, removerImagens, moveItemToCollection ,deleteItemAcervo, getItemAcervo, updateItemAcervo, getImagemItemAcervo };
adicionar imagems, remover imagens e moveItemToCollection não precisam ser exportados

2024-07-25 13:57 UTC, Joao-Pedro-P-Holanda requested changes

2024-07-25 13:57 UTC, Joao-Pedro-P-Holanda commented on firestore.rules
Reverter mudança na regra

2024-07-27 11:48 UTC, Francisco-Paulino-Arruda-Filho commented
const [file, setFile] = useState<File | null>(null);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files.length > 0) {
      setFile(event.target.files[0]);
    }
  };

  const handleButtonClick = async () => {
    if (!file) {
      console.error("No file selected");
      return;
    }

    const newItem = {
      dataDoacao: new Date(),
      nome: "Item domestico",
      descricao: "Descrição",
      colecao: "Item domestico",
      curiosidades: "Curiosidades",
      privado: true,
      imagens: [{
        title: file.name,
        alt: "Imagem",
        src: file
      } as unknown as Imagem]
    } as unknown as ItemAcervo;

    await methodsItemAcervo.adicionarItemAcervo(
      newItem,
      {
        id: "colecoes/privado/lista/Fotografia",
        nome: "Fotografia",
        privado: false,
      } as Colecao
    );
  };

  const editarArquivo = async () => {
    if (!file) {
      console.error("No file selected");
      return;
    }

    const newItem = {
      dataDoacao: new Date(),
      descricao: "Descrição",
      colecao: "Item doméstico",
      nome: "Nome",
      curiosidades: "Curiosidades",
      privado: false,
      imagens: [{
        title: file.name,
        alt: "Imagem",
        src: file
      }] as Array<Imagem>
    } as unknown as ItemAcervo;

    await methodsItemAcervo.updateItemAcervo(
      newItem,
      "colecoes/privado/lista/Fotografia/itens/DlzTWn5Q2pKuF5M4HO8q",
      {
        id: "colecoes/privado/lista/Fotografia",
        nome: "Fotografia",
        privado: false,
      } as Colecao
    );
    COLOCAR DENTRO DO RETURN
    <div style={{ padding: "20px" }}>
      <input type="file" id="file" onChange={handleFileChange} />
      <button onClick={handleButtonClick}>Adicionar</button>
      <button onClick={editarArquivo}>Editar</button>
    </div>
  }
  Código de testes da Home.tsx

2024-07-27 14:01 UTC, Joao-Pedro-P-Holanda requested changes

2024-07-27 14:01 UTC, Joao-Pedro-P-Holanda commented on src/Utils/itemAcervoFirebase.ts
> +      return dataMuseu as ItemAcervo;
Adicionar atributo `id` como docRef.path para não perder a referência ao item

2024-07-31 13:01 UTC, Joao-Pedro-P-Holanda approved these changes

2024-07-31 13:02 UTC, merged