Fix/environment workflows teste
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #163
Opened 2024-08-13 18:49 UTC by Joao-Pedro-P-Holanda

# Feature 

## Resolve

#143 

## Descrição
Removendo ambiente de staging dos testes, em favor de variáveis de ambiente setadas diretamente.

## Alterações

- Adicionando as variáveis de ambiente ao job do cypress em vez de utilizar environments

## Remoções

- Removendo environment em ambos os workflows

## Verificando

### Revisor

- [ ] Funcionalidade verificada localmente
- [ ] Novos testes passam localmente e nos workflows
- [ ] Workflow não cria deployments no pull request

2024-08-14 14:01 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-08-14 14:01 UTC, Francisco-Paulino-Arruda-Filho commented on .github/workflows/component_test.yml
>  jobs:
![image](https://github.com/user-attachments/assets/63fd9b3e-6899-43af-8a41-b901989dbdd7)
Diversos estes falhando localmente
![image](https://github.com/user-attachments/assets/7f255d8a-ae82-4541-bf55-88a11411d345)
E sempre apontando o mesmo erro.

2024-08-14 14:10 UTC, Joao-Pedro-P-Holanda commented on .github/workflows/component_test.yml
>  jobs:
Servidor de desenvolvimento pode conflitar com o cypress nos testes de componente. Type error geralmente acontece por falha do Cypress, tente reiniciar o Cypress sem o servidor de desenvolvimento

2024-08-15 00:46 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-08-15 00:46 UTC, merged