Atualizando CardItemAcervo para receber Item (antes ID); Adicionando …
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #174
Opened 2024-08-17 20:12 UTC by Pedro-Emanuel

# Feature CardItemAcervo

## Resolve

resolve #21 

## Descrição

Criação do componente CardItemAcervo. Recebe um ItemAcervo como parâmetro e retorna um Card desse item.

### Desenvolvedor

## Teste de componente/e2e implementados
- [ ] Deve mostrar uma mensagem pré-definida quando a descrição estiver vazia
- [ ] 

### Revisor

- [ ] Funcionalidade verificada localmente
- [ ] Novos testes passam localmente e nos workflows

2024-08-17 21:18 UTC, Joao-Pedro-P-Holanda requested changes

2024-08-17 21:18 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/__test__/CardItemAcervo.test.tsx
> +    src: 'imagens/img1.jpg',
caminho das imagens é na pasta 'images'

2024-08-17 21:18 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/__test__/CardItemAcervo.test.tsx
> +  });
Imagem não existe no emulador ao iniciar novamente, para garantir que o teste de imagem válida sempre a encontre, adicionarItemAcervo pode ser chamado com o item de mock

2024-08-17 21:18 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/CardItemAcervo.tsx
> +    };
imagem de erro pode ser incluída em assets, a url também deve mudar caso uma exceção ocorra

2024-08-17 21:18 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/CardItemAcervo.tsx
> +          }
Card de item do acervo recebe um item buscado com getItemAcervo, onde as imagens já são retornadas com a src equivalente ao getDownloadUrl, caso a imagem do item comece com "images" ou seja do tipo File e um erro deve ser lançado

2024-08-17 21:18 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/CardItemAcervo.tsx
> +    <Card sx={{ textAlign: 'left', width: '400px' }}>
Adicionar breakpoints para mudar o tamanho máximo na visualização mobile e evitar overflow horizontal 
![image](https://github.com/user-attachments/assets/56536e0c-c85a-40ff-8a78-54adcf4689b9)
![image](https://github.com/user-attachments/assets/27b95b1f-5af6-421e-9112-f1479f655071)

2024-08-17 22:04 UTC, Pedro-Emanuel commented on src/components/CardItemAcervo/__test__/CardItemAcervo.test.tsx
> +  });
já existe um mock? ou eu crio?

2024-08-17 22:26 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/__test__/CardItemAcervo.test.tsx
> +  });
Esse item é considerado o mock, mas corrigindo o comentário anterior: para esse teste basta adicionar uma das imagens na pasta fixtures no caminho "images" do storage antes dos testes começarem

Esse exemplo do copilot converte uma fixture de imagem em Blob, que pode ser adicionado com uploadBytes do firebase, pode haver uma forma mais simples, o importante é adicionar a imagem ao storage antes dos testes
```typescript
cy.fixture('images/default_image.png', 'base64').then((fileContent) => { {
    const blob = Cypress.Blob.base64StringToBlob(fileContent, 'image/png');
}}
```

2024-09-09 23:34 UTC, Joao-Pedro-P-Holanda requested changes

2024-09-09 23:34 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/CardItemAcervo.tsx
> +          <Button variant="contained" color="primary" href={`acervo/item/${item.id}`}>
Caminho é apenas o id completo, sem acervo/item
método getItemAcervo já retorna todo o caminho no id
![image](https://github.com/user-attachments/assets/f2146ae6-af73-4182-afbf-5f69138b9f41)

2024-09-09 23:34 UTC, Joao-Pedro-P-Holanda commented on src/components/CardItemAcervo/CardItemAcervo.tsx
> +          setUrlImagem(url);
Esses dois casos são de imagens inválidas, uma imagem de um item que já existe é uma string como essa, não é necessário verificar o link, apenas que a imagem não seja um arquivo e nem uma referência não salva do storage:
```typescript
"http://127.0.0.1:9199/v0/b/website-museu-jacinto-de-sousa.appspot.com/o/images%2Fimg1.png?alt=media&token=33225db7-a0ee-4b0f-ad65-aca902723560"
```

2024-09-10 00:29 UTC, Pedro-Emanuel reviewed
Mudei a lógica do fetchImageUrl e fiz o botão referenciar o ID.

2024-09-10 00:35 UTC, Joao-Pedro-P-Holanda approved these changes

2024-09-10 00:35 UTC, merged