Feat/exposicoes firebase
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #177
Opened 2024-08-23 22:37 UTC by Joao-Pedro-P-Holanda

# Feature Exposicoes Firebase

## Resolve
resolve #168 

## Descrição
Adicionando métodos de crud do firebase para exposições

## Adições

## Alterações

## Remoções

## Verificando

### Desenvolvedor

- [ ] Teste de componente/e2e implementados

### Revisor

- Criar
    - [ ] Map com os itens e coleções do acervo deve utilizar apenas o id (último segmento do caminho) em ambos

- Get
    - [ ] Itens em uma exposicao buscada com o metodo get devem possuir as suas imagens
    - [ ] Exposicoes buscadas com metodo list devem possuir suas imagens (itens do acervo são guardados apenas como referências)

- Update
    - [ ] Atualizar uma exposicao que possui uma imagem para uma sem imagem deve remover do storage
    - [ ] Atualizar uma exposicao com uma imagem diferente da anterior deve remover a antiga do storage e adicionar a nova
    - [ ] Atualizar uma exposicao sem imagem para uma com imagem deve adicionar ao storage
- Delete
    - [ ] Deletar uma exposicao com imagem deve removê-la do storage

2024-08-23 22:38 UTC, Joao-Pedro-P-Holanda commented
Código usado para testar localmente:
```typescript
import { useEffect, useState } from "react";
import { Colecao } from "../interfaces/Colecao";
import Exposicao from "../interfaces/Exposicao";
import { ClientColecoesFirebase } from "../Utils/colecaoFirebase";
import { ClientExposicaoFirebase } from "../Utils/exposicaoFirebase";
import { adicionarItemAcervo } from "../Utils/itemAcervoFirebase";

const Home = () => {
  const clientColecao = new ClientColecoesFirebase()
  const [colecoes, setColecoes] = useState<Colecao[]>([])
  const [addedCollection, setAddedCollection] = useState<number>(0)
  useEffect(() => {
    clientColecao.getColecoes().then((colecoes) => {
      setColecoes(colecoes)
    })
  }, [addedCollection])

  const client = new ClientExposicaoFirebase();
  return (
    <div style={{ padding: 150 }}>
      <div style={{ display: 'flex', flexDirection: "column" }}>
        <h4>Adicionar coleções e itens de teste</h4>
        <div style={{ display: 'flex' }}>
          <label htmlFor="file-input">Selecionar imagem</label>
          <input type="file" id='file-input' />
        </div>
        <button onClick={async () => {
          const colecao = {
            nome: `Coleção teste ${addedCollection}`,
            descricao: "Coleção de teste",
            privado: false,
          } as Colecao
          console.log(await clientColecao.adicionarColecao(colecao))
          setAddedCollection(addedCollection + 1)
        }}>Adicionar Coleção</button>
        <button onClick={
          async () => {
            const checkbox = document.getElementById('privacy') as HTMLInputElement;
            for (const colecao of colecoes) {
              const itemTeste = {
                nome: `Item teste ${colecao.nome}`,
                descricao: "item de teste",
                curiosidades: "curiosidades",
                dataDoacao: new Date(),
                colecao: colecao.nome,
                doacao: false,
                doacaoAnonima: false,
                nomeDoador: "",
                telefoneDoador: "",
                privado: checkbox.checked,
                imagens: [],
              };
              adicionarItemAcervo(itemTeste, colecao)
            }
          }}>Adicionar Itens de teste nas coleções selecionadas</button>
        <div style={{ display: "flex", gap: 5 }}>

          {colecoes.map((colecao) => (
            <p key={colecao.id}>
              {colecao.nome}
            </p>
          ))}
        </div>
        <div style={{ display: "flex" }}>
          <input type='checkbox' id='privacy'></input>
          <label htmlFor="privacy">Privacidade dos itens</label>
        </div>
        <hr style={{ height: 10, width: '100%', background: "#000" }} />
        <div>
          <h4>Métodos das exposições (necessário mudar itens hardcoded)</h4>
          <button onClick={async () => {
            const fileInput = document.getElementById("file-input") as HTMLInputElement
            const imagem = fileInput?.files[0]
            const exposicao = {
              id: "apsjfdaopfpas",
              nome: "Exposição teste",
              descricao: "Exposição de teste",
              privado: false,
              permanente: false,
              dataInicio: new Date(),
              dataFim: new Date(),
              itensPorColecao: new Map(),
              dataCriacao: new Date(),
            } as Exposicao
            if (imagem) {
              exposicao.imagem = {
                src: imagem,
                title: imagem.name,
                alt: "texto alternativo"
              }
            }
            try {
              await client.adicionarExposicao(exposicao);

            }
            catch (e) {
              console.log(e)
            }

          }}>Adicionar exposição com os itens selecionados</button>
          <button onClick={async () => {
            console.log(await client.listarExposicoes())
          }}>Listar todas as exposições</button>
          <button onClick={async () => {
            const exposicao = await client.getExposicao("/exposicoes/publico/lista/pPZeDt8kIiHpdXqVflz8", true);
            console.log(exposicao);
          }}>Buscar exposição pública</button>
          <button>Buscar exposição privada</button>
          <button
            onClick={async () => {

              const exposicao = {
                id: "/exposicoes/publico/lista/UDAcGzUs6ImuEwth9fsd",
                nome: "Exposição teste",
                descricao: "descrição atualizada",
                privado: true,
                permanente: false,
                dataInicio: new Date(),
                dataFim: new Date(),
                itensPorColecao: new Map(),
                dataCriacao: new Date()
              }
              await client.atualizarExposicao(exposicao)
              console.log(exposicao)
            }}
          >Atualizar exposição mudando a privacidade</button>
          <button onClick={async () => {
            const fileInput = document.getElementById("file-input") as HTMLInputElement
            const imagem = fileInput?.files[0]

            const exposicao = {
              id: "/exposicoes/publico/lista/ifFOBvR3qGyNnd9H9Rpg",
              nome: "Exposição teste",
              descricao: "descrição atualizada",
              privado: false,
              permanente: false,
              dataInicio: new Date(),
              dataFim: new Date(),
              itensPorColecao: new Map(),
              dataCriacao: new Date()
            } as Exposicao
            // if (imagem) {
            //   exposicao.imagem = {
            //     src: imagem,
            //     title: imagem.name,
            //     alt: "texto alternativo"
            //   }
            // }
            await client.atualizarExposicao(exposicao)
            console.log(exposicao)
          }}>Atualizar exposição sem mudar a privacidade</button>
          <button onClick={async () => {
            const id = "/exposicoes/publico/lista/K0ceJTH3xMjnWbKbsJvW"
            await client.deletarExposicao(id)
          }}>Remover exposição</button>
        </div>
      </div >
    </div >
  );
};

export default Home;

```

2024-08-24 00:35 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-08-24 00:35 UTC, Francisco-Paulino-Arruda-Filho commented on src/Utils/colecaoFirebase.ts
>      const privateCollectionsRef = collection(
![image](https://github.com/user-attachments/assets/c342e0af-5b1a-415f-a01e-e5e73f8b8ddd)
Retornando vazio
![image](https://github.com/user-attachments/assets/3d48b0f8-0ce9-430f-b5ba-97cde6583925)

2024-08-24 00:35 UTC, Francisco-Paulino-Arruda-Filho commented on src/Utils/colecaoFirebase.ts
>          const asItemAcervo = doc.data();
![image](https://github.com/user-attachments/assets/aab07ff8-e210-4069-8261-94aca7052b5b)
Criar não adiciona atribibuto de dataCriacao, por isso get falha

2024-08-24 00:35 UTC, Francisco-Paulino-Arruda-Filho commented on src/Utils/converter.ts
> +  omitSet(obj: object, exclude: Set<string>) {
![image](https://github.com/user-attachments/assets/dce23237-ab7e-4e31-9b92-c1a776136217)
Está adicionando em "colecoes" e não em exposições por isso o delete também falha

2024-08-24 00:39 UTC, Joao-Pedro-P-Holanda commented on src/Utils/colecaoFirebase.ts
Em qual função? Os métodos de teste não estão com essa parte comentada? No teste da Home Page eu utilizei um input para adicionar as imagens

2024-08-24 00:40 UTC, Joao-Pedro-P-Holanda commented on src/Utils/colecaoFirebase.ts
>      const privateCollectionsRef = collection(
Qual o caminho completo do item? Como a função foi chamada?

2024-08-24 13:05 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-08-24 13:05 UTC, Francisco-Paulino-Arruda-Filho commented on src/Utils/exposicaoFirebase.ts
> +        await this.#moveExposicao(sendingDoc as Exposicao, newPath);
![Uploading image.png…]()
Erro ao mover exposição

2024-08-24 13:17 UTC, Joao-Pedro-P-Holanda commented on src/Utils/exposicaoFirebase.ts
> +        await this.#moveExposicao(sendingDoc as Exposicao, newPath);
Imagem não carregou

2024-08-24 13:19 UTC, Francisco-Paulino-Arruda-Filho commented on src/Utils/exposicaoFirebase.ts
> +        await this.#moveExposicao(sendingDoc as Exposicao, newPath);
![image](https://github.com/user-attachments/assets/fc5dddfe-3a93-4929-b324-6477f96d1da3)

2024-08-24 14:16 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-08-24 14:16 UTC, merged