Feat/criar item acervo
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #60
Opened 2024-04-23 17:01 UTC by Joao-Pedro-P-Holanda

# Feature Criar Item do Acervo

## Resolve
#35 

## Descrição 
Adicionando novamente página para adicionar um novo item ao acervo, e o componente para visualizar imagens inseridas pelo usuário. Desta vez o ImageCard só deve apresentar as opções para um usuário autenticado

## Adições

- Componente ImageCard com opção de alterar o texto alternativo de uma imagem e de removê-la de acordo com a função onClose passada
- Página CriarItemAcervo, com formulário para inserir um novo item ao acervo, incluindo input de múltiplas imagens
- Adição de bibliotecas para formulários: react-hook-form, mui-tel-input e mui-x/datePicker
- Interface para um item do acervo
- Interface para imagens
- Fixtures de imagens para testes
- Testes de componente para o ImageCard
- Testes ponta a ponta para a página CriarItemAcervo

## Alterações

- Rotas em `App.tsx` embrulhadas em LocalizationProvider
- instâncias do firestore, auth e storage exportadas em `firebase.ts`

## Remoções

- App.css
- index.css

## Verificando
- [ ] Testes unitários implementados
- [ ] Testes ponta a ponta implementados

2024-04-23 17:12 UTC, Joao-Pedro-P-Holanda commented on src/pages/CriarItemAcervo.tsx
> +                  <Select
Label na linha 273

2024-04-23 17:55 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-04-23 17:55 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
> +  it("Deve remover um arquivo ao clicar no botão de remover", () => {
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/4d96b5c3-71e2-49cd-9ca3-9214a210774a)
Teste falhou e quando executo no servidor de desenvolvimento realmente não faz nada

2024-04-23 17:55 UTC, Francisco-Paulino-Arruda-Filho commented on src/components/ImageCard/__tests__/ImageCard.test.tsx
> +
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/01c227b5-bf7f-430d-a380-ed5f8cb0e90b)
Erro não relacionado ao cypress que não permite a execução dos outros testes

2024-04-23 18:02 UTC, Joao-Pedro-P-Holanda commented on cypress/e2e/CriarItemAcervo.test.ts
> +  it("Deve remover um arquivo ao clicar no botão de remover", () => {
qual o erro no console?

2024-04-23 18:09 UTC, Joao-Pedro-P-Holanda commented on src/components/ImageCard/__tests__/ImageCard.test.tsx
> +
Testes de componente não requerem o servidor de desenvolvimento, tente rodar os testes novamente somente com o cypress executando, ou executar primeiro o cypress depois o servidor de desenvolvimento

2024-04-23 18:49 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-04-23 18:49 UTC, Francisco-Paulino-Arruda-Filho commented on src/App.tsx
> +import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/58a80c2d-9898-4c06-92be-612dc95d25d5)
Dependências desatualizadas

2024-04-23 18:51 UTC, Francisco-Paulino-Arruda-Filho commented on src/components/ImageCard/__tests__/ImageCard.test.tsx
> +
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/627215bb-b129-403d-af81-7479e4a98035)
Sem rodar o servidor desenvolvimento tudo falha

2024-04-23 18:57 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
> +  it("Deve remover um arquivo ao clicar no botão de remover", () => {
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/bb5b46c7-d7ba-44ec-8c87-08038cbc2abe)

2024-04-23 18:59 UTC, Joao-Pedro-P-Holanda commented on src/components/ImageCard/__tests__/ImageCard.test.tsx
> +
Somente nos testes de componente, testes e2e precisam do servidor de desenvolvimento

2024-04-23 19:45 UTC, Francisco-Paulino-Arruda-Filho commented
Testes ainda falhando
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/00446275-cc75-47c0-a6a9-cadf8e78ab79)
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/9691e17a-f444-49b3-b39e-f5a2c45ddca0)
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/e660442c-0fae-4015-b1ff-3e3d097b1dd1)
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/371d6e05-fdcf-4828-a015-3d0d13250e34)
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/91481504-53cf-451f-9ab3-b5c4ad1cc937)

2024-04-23 20:49 UTC, Joao-Pedro-P-Holanda commented
> Testes ainda falhando ![image](https://private-user-images.githubusercontent.com/122313737/324974016-00446275-cc75-47c0-a6a9-cadf8e78ab79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDU1NDgsIm5iZiI6MTcxMzkwNTI0OCwicGF0aCI6Ii8xMjIzMTM3MzcvMzI0OTc0MDE2LTAwNDQ2Mjc1LWNjNzUtNDdjMC1hNmE5LWNhZGY4ZTc4YWI3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjIxNDZlMzQ1ODQ1NTI4MDkwMDI3YWVmNzhiNzkzZTg0OWQyZGVhMDU2MGNmZTY4ODUwNjAyZDdjNWY5ZGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PMpD9NHZuQZeAMtx3o6iJsrz0jEyyrO-LBG5OVNuGbA) ![image](https://private-user-images.githubusercontent.com/122313737/324974099-9691e17a-f444-49b3-b39e-f5a2c45ddca0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDU1NDgsIm5iZiI6MTcxMzkwNTI0OCwicGF0aCI6Ii8xMjIzMTM3MzcvMzI0OTc0MDk5LTk2OTFlMTdhLWY0NDQtNDliMy1iMzllLWY1YTJjNDVkZGNhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGI5ZTQ1NzkxZGMxMTIzNzc3MDU0ZTlhMjk3ZDcxNDg4M2I4N2NjZjRlNTY3ZTkyZGQ2ZjdhNDhhZDhjMmJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BByp_4GGXBiuJoAc3m-PnYZW8uTUMWlkeUqKVINfWMo) ![image](https://private-user-images.githubusercontent.com/122313737/324974161-e660442c-0fae-4015-b1ff-3e3d097b1dd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDU1NDgsIm5iZiI6MTcxMzkwNTI0OCwicGF0aCI6Ii8xMjIzMTM3MzcvMzI0OTc0MTYxLWU2NjA0NDJjLTBmYWUtNDAxNS1iMWZmLTNlM2QwOTdiMWRkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTZlN2YxODA5OTIwYzdiNGZlNjFhOTViZTE1NjllMjZmNTVkNGZmZDAyNmU4ZGJlNjA0ZmQ2YzMzM2NlZWY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YgsDQn4oFNmRxyieUvizM6IHJUuyVFt8jD8X41jOibs) ![image](https://private-user-images.githubusercontent.com/122313737/324974228-371d6e05-fdcf-4828-a015-3d0d13250e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDU1NDgsIm5iZiI6MTcxMzkwNTI0OCwicGF0aCI6Ii8xMjIzMTM3MzcvMzI0OTc0MjI4LTM3MWQ2ZTA1LWZkY2YtNDgyOC1hMDE1LTNkMGQxMzI1MGUzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2ExNTdmYmFhNWFhZDE2YWU2MzQ5Zjc3NGJmNjUxM2I0YWQ4ZDQyYzlkMTZmOGYwYWMxYzQwNjJhNzdiZTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v9Y0eAzZctCSL4VTuF3ql7Ul1VsT6MeuzoL4KDCN-EQ) ![image](https://private-user-images.githubusercontent.com/122313737/324974306-91481504-53cf-451f-9ab3-b5c4ad1cc937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDU1NDgsIm5iZiI6MTcxMzkwNTI0OCwicGF0aCI6Ii8xMjIzMTM3MzcvMzI0OTc0MzA2LTkxNDgxNTA0LTUzY2YtNDUxZi05YWIzLWI1YzRhZDFjYzkzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QyMDQ3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MWIxZTFjYTNhYjdmMDQ4ZGQxZmIzYjRmNDY5ODc2NmVlM2FlZTVmN2M1Y2Y3NjkwYTE5NzY4OTJkYTBmNzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ku2AkC6Lrexzizew56MbYZwGVIfhCx9lrda8ZS7hy38)

Servidor de desenvolvimento estava executando? Se sim tentar executar com a opção npm run dev -- --host

2024-04-24 17:36 UTC, Francisco-Paulino-Arruda-Filho commented on src/components/ImageCard/__tests__/ImageCard.test.tsx
Modificar testes após a configuração do emulador #57

2024-04-24 17:37 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-04-24 17:37 UTC, merged