Config/firebase emulators
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #65
Opened 2024-04-25 18:03 UTC by Joao-Pedro-P-Holanda

# Feature Emuladores Firebase

## Resolve
#57 parcialmente
## Descrição 
Adicionando configurações para executar os emuladores do firebase localmente e configurando a suíte de testes para utilizar os emuladores

## Adições

- `emulator_data` contendo os arquivos utilizados em toda sessão do emulador
- Arquivos `.firebaserc, database.rules.json, firebase.json, firestore.indexes.json, firestore.rules e storage.rules` com configurações do firebase
- fixture com o UID do usuário de teste nos emuladores

## Alterações

- Adicionando dependência cypress-firebase e comandos para executar o emulador e o emulador conjuntamente com os testes em `package.json`
- App firebase se conecta aos emuladores quando estiver em ambiente de desenvolvimento, `firebase.ts`
- Configuração do Cypress utiliza o sdk de administrador em `cypress.config.ts`, app firebase declarado em `e2e.ts` 

## Verificando
- [ ] Emulador executa localmente
- [ ] Health-check é sucedido

2024-04-27 12:38 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-04-27 12:40 UTC, Joao-Pedro-P-Holanda commented on cypress.config.ts
> +        credential: admin.credential.cert(
O erro parece ser de dependência faltando, tentar npm install.
Configurações necessárias descrito na especificação dos testes no Notion

2024-04-27 17:02 UTC, Francisco-Paulino-Arruda-Filho commented on cypress.config.ts
> +        credential: admin.credential.cert(
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/b4a557c1-f851-4733-aa74-d745ef631023)
Mesmo erro, agora já rodando npm install e e com o arquivo cypress.env.json
![firebse](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/dada7547-184d-4809-9562-b650c08a5ff5)

2024-04-27 17:45 UTC, Joao-Pedro-P-Holanda commented on cypress.config.ts
> +        credential: admin.credential.cert(
Cypress.env.json também precisa das variáveis de ambiente relativas ao Firebase, _que não são compartilhadas no notion ou github_

2024-04-27 18:59 UTC, Francisco-Paulino-Arruda-Filho commented on cypress.config.ts
> +        credential: admin.credential.cert(
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/6ef7a662-789f-4fe7-a151-540f0f47894a)
Erro ao executar  health check

2024-04-27 19:02 UTC, Joao-Pedro-P-Holanda commented on cypress.config.ts
> +        credential: admin.credential.cert(
Variáveis para inicializar o firebase estão definidas em cypress.env.json? **Não copiá-las na conversa**, conferir se as mesmas variáveis usadas em `firebase/firebase.ts` estão sendo utilizadas

2024-04-28 17:50 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-04-28 17:50 UTC, merged