Refactor/criar item acervo
PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa pull request #90
Opened 2024-05-03 18:22 UTC by Joao-Pedro-P-Holanda

# Refatoração Criar Item do Acervo

## Resolve
#70 

## Descrição
Refatorando Página de criar item do acervo, movendo funcionalidades de comunicação com o firebase para arquivos utilitários, e utilizando hooks customizados para acessar essas funções

## Adições

- hook para o formulário de um item do acervo
- hook para a lista de coleções
- funções para adicionar um item do acervo ao firestore e as imagens ao storage
- caso de teste de inserir um item com imagens

## Alterações

- utilizando hook de formulário para item do acervo em vez de useForm diretamente
- Transformando collectionList em objeto simples e removendo estado
- regras do storage permitem leitura por qualquer usuário e escrita por usuários logados

## Remoções

- removendo useEffect de collectionList
- removendo métodos `submitToStorage`, `submitToFirestore` e `removeFromStorage` de CriarItemAcervo.tsx 

## Verificando

### Desenvolvedor

- [ ] Teste de componente/e2e implementados

### Revisor

- [ ] Funcionalidade verificada localmente
- [ ] Novos testes passam localmente e nos workflows

2024-05-09 17:57 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/4002bded-168b-4641-af30-cf6aac15aab3)
Falha no teste

2024-05-09 17:59 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/6a832c2a-43b5-45ce-8998-c5efc3028ea5)
No caso falha no workflow do gitHub

2024-05-09 18:04 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/6a9ab356-5ce6-4f2f-90ed-ef5c5759f460)
Teste fahnadi localmente
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/af602501-1d9d-4555-8dd9-c8ce168a0787)

2024-05-09 18:06 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-05-09 18:06 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/ab34f5ca-28fc-489c-a6df-2e650831a99a)
Esse é o teste falhando

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/4ab33155-ac39-4b14-add7-aee7f2038cb1)
Teste de renderização falhando

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
>    beforeEach(() => {
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/d36c14ef-3d14-4233-9e4f-454538444d83)

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/c1b7d99b-4bec-41f9-9387-89fc179d0718)
De criar item falhando

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/d2b0c03e-ebeb-4f84-9c07-9540414ee4f9)
Erro no teste da mensagem de erro

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/c1c8de4f-b8f0-405a-a822-120b47ac6cfb)
Erro ao criar item anonimamente

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/64323b00-15aa-460b-9bd7-2c0ecb0f1738)

2024-05-15 12:46 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/4c954377-fd4b-4612-9c0d-5d2f7dbae1f9)
Erro no teste de criar item não doado

2024-05-15 13:27 UTC, Joao-Pedro-P-Holanda commented on cypress/e2e/CriarItemAcervo.test.ts
Erro na renderização para visualização desktop indica uma variável de ambiente faltando, os outros erros não estão mostrando qual foi o erro exato

2024-05-18 16:47 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
Deve criar um item de acervo com a imagem passada
Deve criar um item de acervofailed
Deve exibir mensagem de erro ao tentar criar um item de acervo sem preencher o nome do doador
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/6a8a11f7-219d-4130-89c4-62f85cafc314)
Não achou elemento esperado

2024-05-18 16:47 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/7e05ad5b-35b0-4a3d-8aa6-6828ba68c2d4)
Deve criar um item de acervofailed
Deve exibir mensagem de erro ao tentar criar um item de acervo sem preencher a data

2024-05-18 16:48 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
>    beforeEach(() => {
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/e124ed75-a11d-4d26-9510-af7bce1985e8)
Outro elemento não encontrado

2024-05-18 17:30 UTC, Joao-Pedro-P-Holanda commented on cypress/e2e/CriarItemAcervo.test.ts
>    beforeEach(() => {
Verificando:

- [ ] Apenas o servidor de desenvolvimento dessa branch executando
- [ ] Emulador executando normalmente (log pode ser visualizado em: http://localhost:4000/logs)
- [ ] Último commit na branch local é a87bd4e88ee69313b89b5a9c2d9f0c0c786250ad

1. Qual o navegador usado?
2. Os mesmos casos de teste falham ao executar novamente, ou os erros mudam ao executar de novo?

2024-05-18 18:51 UTC, Francisco-Paulino-Arruda-Filho commented on cypress/e2e/CriarItemAcervo.test.ts
>    beforeEach(() => {
Revisor:
- [x] Estou com apenas o server de desenvolvimento dessa branch executando
- [x] Emulador executando corretamente
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/78dd1970-980e-4838-89ce-b52dfe752b74)
- [x] Último commit é esse mesmo
![image](https://github.com/PI-II-Museu-Historico-Jacinto-de-Sousa/website-museu-jacinto-sousa/assets/122313737/ad6b1594-99f1-406c-bd63-f1be1fc3f28c)

1. Google Chrome.
2.  Os erros variam de execução para execução.

2024-05-18 19:11 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-05-18 19:11 UTC, merged